import React, { useState, useEffect } from "react";
import {
  Box, Container, Typography, Card, CardContent, Button, Chip, LinearProgress,
  Checkbox, Accordion, AccordionSummary, AccordionDetails, CircularProgress,
  Alert, Grid, Link,
} from "@mui/material";
import {
  ExpandMore, CheckCircle, School, ArrowBack, OpenInNew, Star, Print,
} from "@mui/icons-material";
import { useNavigate, useParams } from "react-router-dom";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";

const DIFFICULTY_COLORS = { Beginner: "#10B981", Intermediate: "#3B82F6", Advanced: "#F59E0B", Expert: "#EF4444" };
const RESOURCE_ICONS = { Course: "📚", Tutorial: "📖", Documentation: "📄", Practice: "💻", Video: "🎥", Book: "📕" };
const PLATFORM_COLORS = { freeCodeCamp: "#F03000", Coursera: "#0056D2", YouTube: "#FF0000", Kaggle: "#20BEFF", HackerRank: "#00EA64", W3Schools: "#04AA6D", default: "#6C63FF" };

const printStyles = `
  @media print {
    /* Hide everything first */
    body * { visibility: hidden; }
    
    /* Show only the print document */
    #print-document, #print-document * { visibility: visible; }
    
    #print-document {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      background: white;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    @page {
      margin: 15mm;
      size: A4;
    }
  }
`;

function PrintDocument({ roadmap, completedSteps }) {
  if (!roadmap) return null;
  const progress = roadmap.steps?.length > 0 ? Math.round((completedSteps.length / roadmap.steps.length) * 100) : 0;

  return (
    <div id="print-document" style={{ display: 'none', fontFamily: 'Arial, sans-serif', color: '#111', background: 'white', padding: '30px 40px' }}>
      {/* Header */}
      <div style={{ borderBottom: '3px solid #6C63FF', paddingBottom: 16, marginBottom: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ fontSize: 11, color: '#6C63FF', fontWeight: 700, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 6 }}>
              🎓 CareerAI — Learning Roadmap
            </div>
            <h1 style={{ margin: 0, fontSize: 28, fontWeight: 900, color: '#111' }}>{roadmap.careerField}</h1>
            <p style={{ margin: '6px 0 0', fontSize: 13, color: '#555' }}>
              ⏱️ Duration: {roadmap.totalDuration} &nbsp;|&nbsp; {roadmap.steps?.length} Steps &nbsp;|&nbsp; Progress: {progress}% ({completedSteps.length}/{roadmap.steps?.length} completed)
            </p>
          </div>
          <div style={{ textAlign: 'right', fontSize: 11, color: '#888' }}>
            <div>Generated by CareerAI</div>
            <div>{new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
          </div>
        </div>

        {/* Progress bar */}
        <div style={{ marginTop: 12, background: '#e0e0e0', borderRadius: 10, height: 8, overflow: 'hidden' }}>
          <div style={{ width: `${progress}%`, background: 'linear-gradient(90deg, #6C63FF, #00D4AA)', height: '100%', borderRadius: 10 }} />
        </div>
      </div>

      {/* Steps */}
      {roadmap.steps?.map((step, idx) => {
        const isCompleted = completedSteps.includes(step.stepNumber);
        return (
          <div key={step.stepNumber} style={{ marginBottom: 20, pageBreakInside: 'avoid', border: '1px solid #e0e0e0', borderRadius: 8, overflow: 'hidden' }}>
            {/* Step header */}
            <div style={{ background: isCompleted ? '#f0fdf4' : '#f8f9ff', padding: '12px 16px', borderBottom: '1px solid #e0e0e0', display: 'flex', alignItems: 'center', gap: 12 }}>
              <div style={{ width: 28, height: 28, borderRadius: '50%', background: isCompleted ? '#10B981' : '#6C63FF', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 900, flexShrink: 0 }}>
                {isCompleted ? '✓' : step.stepNumber}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3, flexWrap: 'wrap' }}>
                  <span style={{ fontSize: 10, fontWeight: 700, color: '#6C63FF', textTransform: 'uppercase', letterSpacing: 1 }}>STEP {step.stepNumber}</span>
                  {step.milestone && <span style={{ fontSize: 10, background: '#FEF3C7', color: '#D97706', padding: '1px 7px', borderRadius: 10, fontWeight: 700 }}>⭐ Milestone</span>}
                  <span style={{ fontSize: 10, background: '#EEF2FF', color: DIFFICULTY_COLORS[step.difficulty] || '#6C63FF', padding: '1px 7px', borderRadius: 10, fontWeight: 600 }}>{step.difficulty}</span>
                  <span style={{ fontSize: 10, color: '#888' }}>⏱️ {step.duration}</span>
                  {isCompleted && <span style={{ fontSize: 10, background: '#F0FDF4', color: '#10B981', padding: '1px 7px', borderRadius: 10, fontWeight: 700 }}>✅ Completed</span>}
                </div>
                <div style={{ fontSize: 15, fontWeight: 800, color: '#111' }}>{step.title}</div>
              </div>
            </div>

            {/* Step body */}
            <div style={{ padding: '12px 16px', background: 'white' }}>
              <p style={{ margin: '0 0 12px', fontSize: 12, color: '#444', lineHeight: 1.6 }}>{step.description}</p>

              {/* Skills */}
              {step.skills?.length > 0 && (
                <div style={{ marginBottom: 12 }}>
                  <div style={{ fontSize: 10, fontWeight: 700, color: '#888', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 }}>Skills you'll learn</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                    {step.skills.map(s => (
                      <span key={s} style={{ fontSize: 11, background: '#EEF2FF', color: '#6C63FF', padding: '2px 8px', borderRadius: 12, fontWeight: 600, border: '1px solid #C7D2FE' }}>{s}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Resources */}
              {step.resources?.length > 0 && (
                <div>
                  <div style={{ fontSize: 10, fontWeight: 700, color: '#888', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 }}>Resources</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                    {step.resources.map((r, ri) => (
                      <div key={ri} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 10px', background: '#f9f9f9', borderRadius: 6, border: '1px solid #eee' }}>
                        <span style={{ fontSize: 13 }}>{RESOURCE_ICONS[r.type] || '📌'}</span>
                        <div style={{ flex: 1 }}>
                          <span style={{ fontSize: 10, fontWeight: 700, color: '#666', textTransform: 'uppercase' }}>{r.platform} &nbsp;</span>
                          <span style={{ fontSize: 12, color: '#333', fontWeight: 600 }}>{r.title}</span>
                        </div>
                        {r.isFree && <span style={{ fontSize: 10, background: '#F0FDF4', color: '#10B981', padding: '1px 6px', borderRadius: 8, fontWeight: 700, border: '1px solid #BBF7D0' }}>FREE</span>}
                        <span style={{ fontSize: 10, color: '#6C63FF' }}>{r.url}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        );
      })}

      {/* Footer */}
      <div style={{ marginTop: 24, paddingTop: 12, borderTop: '1px solid #e0e0e0', display: 'flex', justifyContent: 'space-between', fontSize: 10, color: '#999' }}>
        <span>CareerAI — AI Student Support System for Career Path Guidance</span>
        <span>{roadmap.careerField} Learning Roadmap</span>
      </div>
    </div>
  );
}

export default function RoadmapPage() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const { user, isAuthenticated } = useAuth();
  const [roadmap, setRoadmap] = useState(null);
  const [completedSteps, setCompletedSteps] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [expanded, setExpanded] = useState(0);

  useEffect(() => {
    const fetch = async () => {
      try {
        const res = await api.get(`/roadmap/${slug}`);
        setRoadmap(res.data.roadmap);
        if (res.data.userProgress) {
          setCompletedSteps(res.data.userProgress.completedSteps || []);
        }
      } catch (e) {
        setError("Roadmap not found for this career field.");
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [slug]);

  const handlePrint = () => {
    // Show print document and print
    const printDoc = document.getElementById('print-document');
    if (printDoc) printDoc.style.display = 'block';
    window.print();
    if (printDoc) printDoc.style.display = 'none';
  };

  const toggleStep = async (stepNumber) => {
    const newCompleted = completedSteps.includes(stepNumber)
      ? completedSteps.filter((s) => s !== stepNumber)
      : [...completedSteps, stepNumber];
    setCompletedSteps(newCompleted);
    if (isAuthenticated) {
      setSaving(true);
      try {
        await api.put(`/roadmap/${slug}/progress`, { completedSteps: newCompleted });
      } catch (e) { console.error("Failed to save progress"); }
      finally { setSaving(false); }
    }
  };

  if (loading) return <Box sx={{ minHeight: "100vh", bgcolor: "#0A0E1A", display: "flex", alignItems: "center", justifyContent: "center" }}><CircularProgress /></Box>;
  if (error || !roadmap) return <Box sx={{ minHeight: "100vh", bgcolor: "#0A0E1A", display: "flex", alignItems: "center", justifyContent: "center" }}><Alert severity="warning">{error || "Roadmap not available yet for this career."}</Alert></Box>;

  const progress = roadmap.steps?.length > 0 ? Math.round((completedSteps.length / roadmap.steps.length) * 100) : 0;

  return (
    <Box sx={{ minHeight: "100vh", bgcolor: "#0A0E1A", py: 5 }}>
      <style>{printStyles}</style>

      {/* Hidden print document */}
      <PrintDocument roadmap={roadmap} completedSteps={completedSteps} />

      <Container maxWidth="lg">
        {/* Back + Print buttons */}
        <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 3 }}>
          <Button startIcon={<ArrowBack />} onClick={() => navigate(-1)} sx={{ color: "text.secondary" }}>Back</Button>
          <Button variant="outlined" startIcon={<Print />} onClick={handlePrint}
            sx={{ borderColor: "rgba(255,255,255,0.2)", color: "text.secondary", "&:hover": { borderColor: "primary.main", color: "primary.main" } }}>
            Print / Save PDF
          </Button>
        </Box>

        {/* Header Card */}
        <Card sx={{ background: "linear-gradient(135deg, rgba(108,99,255,0.1), rgba(0,212,170,0.05))", border: "1px solid rgba(108,99,255,0.2)", mb: 4 }}>
          <CardContent sx={{ p: { xs: 3, md: 4 } }}>
            <Grid container spacing={3} alignItems="center">
              <Grid item xs={12} md={8}>
                <Chip icon={<School sx={{ fontSize: "14px !important" }} />} label="Learning Roadmap" sx={{ mb: 2, bgcolor: "rgba(108,99,255,0.15)", color: "#9C94FF" }} />
                <Typography variant="h3" sx={{ fontWeight: 800, mb: 1 }}>{roadmap.careerField}</Typography>
                <Typography color="text.secondary">⏱️ Estimated duration: {roadmap.totalDuration} &nbsp;•&nbsp; {roadmap.steps?.length} learning steps</Typography>
              </Grid>
              <Grid item xs={12} md={4}>
                <Box sx={{ textAlign: { md: "right" } }}>
                  <Typography variant="h2" sx={{ fontWeight: 900, background: "linear-gradient(135deg, #6C63FF, #00D4AA)", backgroundClip: "text", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
                    {progress}%
                  </Typography>
                  <Typography color="text.secondary" variant="body2" sx={{ mb: 1.5 }}>
                    {completedSteps.length}/{roadmap.steps?.length} steps completed
                  </Typography>
                  <LinearProgress variant="determinate" value={progress}
                    sx={{ height: 10, borderRadius: 10, bgcolor: "rgba(255,255,255,0.06)", "& .MuiLinearProgress-bar": { background: "linear-gradient(90deg, #6C63FF, #00D4AA)", borderRadius: 10 } }} />
                  {!isAuthenticated && (
                    <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: "block" }}>
                      <Link component="button" onClick={() => navigate("/register")} sx={{ color: "primary.light", cursor: "pointer" }}>Create account</Link> to save progress
                    </Typography>
                  )}
                  {saving && <Typography variant="caption" color="text.secondary">Saving...</Typography>}
                </Box>
              </Grid>
            </Grid>
          </CardContent>
        </Card>

        {/* Steps */}
        <Box sx={{ position: "relative" }}>
          <Box sx={{ position: "absolute", left: { xs: 20, md: 28 }, top: 0, bottom: 0, width: 2, bgcolor: "rgba(255,255,255,0.06)", zIndex: 0 }} />
          {roadmap.steps?.map((step, idx) => {
            const isCompleted = completedSteps.includes(step.stepNumber);
            return (
              <Box key={step.stepNumber} sx={{ position: "relative", pl: { xs: 7, md: 9 }, mb: 3 }}>
                <Box onClick={() => toggleStep(step.stepNumber)} sx={{
                  position: "absolute", left: { xs: 12, md: 20 }, top: 20, width: 18, height: 18,
                  borderRadius: "50%", cursor: "pointer", zIndex: 1, display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s",
                  bgcolor: isCompleted ? "#00D4AA" : "rgba(255,255,255,0.1)", border: `2px solid ${isCompleted ? "#00D4AA" : "rgba(255,255,255,0.2)"}`,
                  "&:hover": { transform: "scale(1.3)", borderColor: "#00D4AA" },
                }}>
                  {isCompleted && <CheckCircle sx={{ fontSize: 12, color: "white" }} />}
                </Box>
                <Accordion expanded={expanded === idx} onChange={() => setExpanded(expanded === idx ? -1 : idx)}
                  sx={{ background: isCompleted ? "rgba(0,212,170,0.05)" : "rgba(17,24,39,0.95)", border: `1px solid ${isCompleted ? "rgba(0,212,170,0.25)" : "rgba(255,255,255,0.06)"}`, borderRadius: "12px !important", "&:before": { display: "none" }, mb: 0 }}>
                  <AccordionSummary expandIcon={<ExpandMore />} sx={{ px: 3, py: 1.5 }}>
                    <Box sx={{ display: "flex", alignItems: "center", gap: 2, width: "100%", mr: 2 }}>
                      <Checkbox checked={isCompleted} onChange={() => toggleStep(step.stepNumber)} onClick={(e) => e.stopPropagation()}
                        sx={{ p: 0, color: "rgba(255,255,255,0.2)", "&.Mui-checked": { color: "#00D4AA" } }} />
                      <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5, flexWrap: "wrap" }}>
                          <Typography variant="caption" sx={{ color: "primary.main", fontWeight: 700 }}>STEP {step.stepNumber}</Typography>
                          {step.milestone && <Chip label="Milestone" size="small" icon={<Star sx={{ fontSize: "12px !important", color: "#F59E0B !important" }} />} sx={{ bgcolor: "rgba(245,158,11,0.1)", color: "#F59E0B", border: "1px solid rgba(245,158,11,0.3)", height: 20, fontSize: 10 }} />}
                          <Chip label={step.difficulty} size="small" sx={{ bgcolor: `${DIFFICULTY_COLORS[step.difficulty]}15`, color: DIFFICULTY_COLORS[step.difficulty], height: 20, fontSize: 10 }} />
                          <Typography variant="caption" color="text.secondary">⏱️ {step.duration}</Typography>
                        </Box>
                        <Typography variant="h6" sx={{ fontWeight: 700, mt: 0.3, textDecoration: isCompleted ? "line-through" : "none", opacity: isCompleted ? 0.6 : 1 }}>{step.title}</Typography>
                      </Box>
                    </Box>
                  </AccordionSummary>
                  <AccordionDetails sx={{ px: 3, pb: 3 }}>
                    <Typography color="text.secondary" sx={{ mb: 3, lineHeight: 1.7 }}>{step.description}</Typography>
                    {step.skills?.length > 0 && (
                      <Box sx={{ mb: 3 }}>
                        <Typography variant="caption" sx={{ fontWeight: 700, color: "text.secondary", textTransform: "uppercase", letterSpacing: 1 }}>Skills you'll learn</Typography>
                        <Box sx={{ display: "flex", flexWrap: "wrap", gap: 1, mt: 1 }}>
                          {step.skills.map((s) => <Chip key={s} label={s} size="small" sx={{ bgcolor: "rgba(108,99,255,0.12)", color: "#9C94FF", border: "1px solid rgba(108,99,255,0.25)" }} />)}
                        </Box>
                      </Box>
                    )}
                    {step.resources?.length > 0 && (
                      <Box>
                        <Typography variant="caption" sx={{ fontWeight: 700, color: "text.secondary", textTransform: "uppercase", letterSpacing: 1 }}>Resources</Typography>
                        <Grid container spacing={1.5} sx={{ mt: 0.5 }}>
                          {step.resources.map((r, ri) => (
                            <Grid item xs={12} sm={6} key={ri}>
                              <Box component={Link} href={r.url} target="_blank" rel="noopener noreferrer" underline="none"
                                sx={{ display: "flex", alignItems: "center", gap: 1.5, p: 1.5, borderRadius: 2, bgcolor: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", cursor: "pointer", transition: "all 0.2s", "&:hover": { bgcolor: "rgba(255,255,255,0.07)", borderColor: PLATFORM_COLORS[r.platform] || PLATFORM_COLORS.default } }}>
                                <Typography sx={{ fontSize: "1.1rem" }}>{RESOURCE_ICONS[r.type] || "📌"}</Typography>
                                <Box sx={{ flex: 1, minWidth: 0 }}>
                                  <Typography variant="caption" sx={{ fontWeight: 700, display: "block", color: PLATFORM_COLORS[r.platform] || PLATFORM_COLORS.default, fontSize: 10, textTransform: "uppercase" }}>{r.platform}</Typography>
                                  <Typography variant="body2" sx={{ fontWeight: 600, color: "text.primary", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.title}</Typography>
                                </Box>
                                <Box sx={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 0.3 }}>
                                  <OpenInNew sx={{ fontSize: 14, color: "text.secondary" }} />
                                  {r.isFree && <Chip label="Free" size="small" sx={{ height: 16, fontSize: 9, bgcolor: "rgba(16,185,129,0.15)", color: "#10B981" }} />}
                                </Box>
                              </Box>
                            </Grid>
                          ))}
                        </Grid>
                      </Box>
                    )}
                  </AccordionDetails>
                </Accordion>
              </Box>
            );
          })}
        </Box>

        {progress === 100 && (
          <Card sx={{ mt: 4, background: "linear-gradient(135deg, rgba(0,212,170,0.15), rgba(16,185,129,0.05))", border: "1px solid rgba(0,212,170,0.3)", textAlign: "center" }}>
            <CardContent sx={{ py: 4 }}>
              <Typography sx={{ fontSize: "3rem", mb: 1 }}>🎉</Typography>
              <Typography variant="h4" sx={{ fontWeight: 800, color: "#00D4AA", mb: 1 }}>Roadmap Complete!</Typography>
              <Typography color="text.secondary" sx={{ mb: 3 }}>You've completed all steps in the {roadmap.careerField} roadmap. Ready for your next challenge?</Typography>
              <Button variant="contained" onClick={() => navigate("/explore")} sx={{ background: "linear-gradient(135deg, #6C63FF, #00D4AA)", mr: 2 }}>Explore More Careers</Button>
              <Button variant="outlined" onClick={() => navigate("/dashboard")} sx={{ borderColor: "rgba(255,255,255,0.15)" }}>Dashboard</Button>
            </CardContent>
          </Card>
        )}
      </Container>
    </Box>
  );
}